[Travis] Switched to using Flex for testing
ezsystems/ezplatform-content-forms pull request #38
Opened 2021-02-18 15:11 UTC by mnocon

2021-02-24 11:21 UTC, mnocon commented on bin/.travis/prepare_unittest.sh
> -#!/bin/sh
This script has been removed as it was doing anything relevant anymore

2021-02-24 11:22 UTC, mnocon commented on .travis.yml
> +  - if [ "$BEHAT_OPTS" != "" ] ; then cd "$HOME/build/project"; docker-compose exec --user www-data app sh -c "mkdir -p config/packages/behat/" ; fi
Right now this directory does not exist - I create it manually for these tests to pass, we might add a recipe that creates it in the future (but it's a bit too early IMHO to do that, and an artificial recipe just to create a directory seems like an overkill).

2021-03-08 10:03 UTC, bogusez requested changes

2021-03-08 10:03 UTC, bogusez commented on .travis.yml
> +  - if [ "${BEHAT_OPTS}" != "" ]; then ./vendor/bin/prepare_project_edition.sh oss ${PROJECT_VERSION} ${COMPOSE_FILE} ; fi
space needed

2021-03-08 10:23 UTC, mnocon commented on .travis.yml
> +  - if [ "${BEHAT_OPTS}" != "" ]; then ./vendor/bin/prepare_project_edition.sh oss ${PROJECT_VERSION} ${COMPOSE_FILE} ; fi
Thanks, fixed!

2021-03-08 10:24 UTC, bogusez approved these changes

2021-03-10 08:39 UTC, merged