IBX-6495: Fixed saving non-translatable fields in main language
ezsystems/ezplatform-content-forms pull request #74
Opened 2023-09-19 13:30 UTC by barw4

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-6495](https://issues.ibexa.co/browse/IBX-6495)
| **Type**                                   | bug
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

An additional check was added to ensure that saving new non-translatable values in the same language as a main language won't be reverted.

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/engineering-team`).

2023-09-26 08:18 UTC, webhdx requested changes

2023-09-26 08:18 UTC, webhdx commented on src/lib/Data/Mapper/ContentUpdateMapper.php
> +                        : $field->value,
Please extract these conditions to separate variables with descriptive names. In current form it's highly unreadable.

2023-09-26 08:26 UTC, webhdx approved these changes

2023-09-26 13:34 UTC, konradoboza approved these changes

2023-09-28 09:25 UTC, tomaszszopinski approved these changes
QA approved on IbexaDXP 3.3 commerce.

2023-09-28 09:53 UTC, merged